site_name: Geoladris - Core
pages:
- Home: index.md
- 'Plugins': plugins.md
- 'Configurando aplicaciones': configuring_apps.md
- 'Empaquetando aplicaciones': packaging.md
- 'Migrando plugins': migrating.md
- 'Change log': changelog.md
- 'Desarrollador': developer.md

